### ISSUE TITLE
Azure Storage Image Hosting

### ISSUE THREAD

**Issue by NickBrooks** [felixrieseberg/Ghost-Azure#10]
Just looking at the default location for image uploads, it is the default for Ghost which is `/content/images/`... is there a plan to move this to true Azure Storage hosting for something like `https://XXX.blob.core.windows.net/container/image.jpg`??

**Comment by felixrieseberg** [comment]
Hey @NickBrooks, thanks for asking - I don't want to change Ghost in any way, so not in this repo. Ghost does support custom image storage providers (https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module), but I don't think that one for Azure Blob storage is available yet... So it's still looking for a brave hero to build it ;-)

I'll be closing this issue in the meantime.

**Comment by TerribleDev** [comment]
Hmm... I think I may try to do this, sometime this weekend...

**Comment by NickBrooks** [comment]
That'd be awesome, let me know if you need any help. Just makes a lot of
sense if you start to create a lot of content!

**Comment by TerribleDev** [comment]
Agreed, I like the idea. I'm def gunna do this over the weekend

**Comment by TerribleDev** [comment]
@NickBrooks @felixrieseberg https://github.com/tparnell8/ghost-azurestorage I mostly do client side js (and by mostly I mean thats pretty much all I do) Please feel free to submit pr's to remove any derpy-ness you see

**Comment by NickBrooks** [comment]
Looks good I'll take a look on Monday!

**Comment by TerribleDev** [comment]
It totally works atleast! I was able to use it to host things in storage...

**Comment by felixrieseberg** [comment]
Awesome, super well done. I'll reference it in the readme :fireworks:!
