### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by acb122** [felixrieseberg/Ghost-Azure#11]
I pushed broken code to my server by accident but then fixed it but my server is still down how do i get azure to restart? i have tried running npm start --production

**Comment by felixrieseberg** [comment]
Just restart your website!

**Comment by acb122** [comment]
i get this 

> npm start
> D:\home\site\wwwroot

module.js:340
    throw err;
          ^
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\express-hbs\lib\hbs.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\express-hbs\index.js:1:80)

npm ERR! ghost@0.7.0 start: `node index`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ghost@0.7.0 start script.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "node" "D:\Program Files (x86)\npm\1.4.9\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE

**Comment by acb122** [comment]
i added a new package and it has broken it. it runs locally fine

**Comment by TerribleDev** [comment]
can you run npm install?

**Comment by acb122** [comment]
i get this 
npm install
D:\home\site\wwwroot
npm http GET https://registry.npmjs.org/unidecode/-/unidecode-0.1.3.tgz
npm http GET https://registry.npmjs.org/bookshelf/-/bookshelf-0.7.9.tgz
npm http GET https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.1.0.tgz
npm http GET https://registry.npmjs.org/knex/-/knex-0.7.3.tgz
npm http GET https://registry.npmjs.org/lodash/-/lodash-3.10.0.tgz
npm http 200 https://registry.npmjs.org/unidecode/-/unidecode-0.1.3.tgz
npm http 200 https://registry.npmjs.org/bookshelf/-/bookshelf-0.7.9.tgz
npm http 200 https://registry.npmjs.org/knex/-/knex-0.7.3.tgz
npm http 200 https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.1.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-3.10.0.tgz
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\bookshelf requires lodash@'^2.0.0' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\knex requires chalk@'~0.5.1' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\knex requires lodash@'~2.4.0' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\busboy\node_modules\dicer requires readable-stream@'1.1.x' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\bower\node_modules\inquirer\node_modules\chalk\node_modules\strip-ansi requires ansi-regex@'^0.2.1' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\bower\node_modules\inquirer\node_modules\ansi-regex,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\grunt-contrib-jshint\node_modules\jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\grunt-docker\node_modules\docker\node_modules\pygmentize-bundled requires mkdirp@'~0.3.5' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\grunt-docker\node_modules\docker\node_modules\mkdirp,
npm WARN unmet dependency which is version 0.3.2
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\grunt-jscs\node_modules\jscs requires glob@'^5.0.1' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\glob,
npm WARN unmet dependency which is version 4.3.2
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-parser requires debug@'0.7.4' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\debug,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client requires debug@'1.0.4' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client requires parseuri@'0.0.4' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\parseuri,
npm WARN unmet dependency which is version 0.0.2
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\tap\node_modules\difflet requires charm@'0.1.x' but will load
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\charm,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency D:\home\site\wwwroot\node_modules\testem\node_modules\tap\node_modules\glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined

**Comment by NickBrooks** [comment]
What package's have you tried to install?

**Comment by acb122** [comment]
https://www.npmjs.com/package/x-frame-options

**Comment by acb122** [comment]
i tried reverting my changes and redeploying but it still wont start
