### ISSUE TITLE
Some issues with the Ghost deployed on Azure

### ISSUE THREAD

**Issue by johnluo** [felixrieseberg/Ghost-Azure#15]
Dear Sir,

Once I deployed the Ghost on Azure, faced the issues. "Updating Website Config” kept going and never stop, I get some error screenshots from My Azure account for you reference as below.  

![ghost-1](https://cloud.githubusercontent.com/assets/1750848/11553127/b788a7bc-99c6-11e5-96b5-57860355207e.png)
![ghost-2](https://cloud.githubusercontent.com/assets/1750848/11553128/b872d9c2-99c6-11e5-8704-f068c5967a3a.png)
![ghost-3](https://cloud.githubusercontent.com/assets/1750848/11553129/b9d387ee-99c6-11e5-9d43-6e18c5da39c8.png)

Thanks

Best Regards,
John

**Comment by felixrieseberg** [comment]
Thanks for reporting! I'm sorry to say that I have trouble reproducing your issue - could you do me a favor and try deploying again? Out of 500 deployments, one or two might fail for performance reasons, so I'm afraid that you're just one of the unlucky ones.

**Comment by johnluo** [comment]
Dear Sir,

I have tried many times(>10) today, the result is the same.

Any Advice?

![ghost-4](https://cloud.githubusercontent.com/assets/1750848/11580206/d5109354-9a6f-11e5-9a89-b31f71dd7f45.png)

Thanks

**Comment by felixrieseberg** [comment]
Hm... I'm stumped. You're just clicking the "Deploy to Azure" button in the readme, right?

**Comment by pizycki** [comment]
I have the same situation. Config update phase just keeps spinning and spinning.

**Comment by johnluo** [comment]
@felixrieseberg 

Yup！

![ghost-6](https://cloud.githubusercontent.com/assets/1750848/11608082/a404ecc0-9b9a-11e5-9c20-af4e6b7cde3a.jpg)

**Comment by felixrieseberg** [comment]
_Super_ weird. I'm so sorry for this, but I have no idea what's wrong. @davidebbo is the currently reigning king of Azure Web Apps - do you have any idea what could be wrong here?

**Comment by davidebbo** [comment]
Not sure. If you can share the info below as text, it should be possible for someone here to investigate further (info in screenshots is not easily consumable).

Also, as a test, does this simpler repo work for you? https://github.com/Tuesdaysgreen/HelloWorlddemo

**Comment by johnluo** [comment]
@davidebbo Done and seems no any issues.

Submitting Deployment
Deployment Started
Creating Web Hosting Plan
Creating Website
Setting up Source Control
Fetching changes. 
Deployment Complete
Manage your site / Browse to http://helloworld-tesing.azurewebsites.net

Access the URL, I can see 'Hello World 8'

Thanks

**Comment by johnluo** [comment]
@davidebbo 

Dear David,

Pls refer below text info for deploying Ghost to Azure again. 

---

OPERATION ID
4FA7EDD0706EA36E
TRACKING ID
b84bdf3c-87ca-41c8-89e0-7eaf4d31605f
STATUS
BadGateway
PROVISIONING STATE
Running
TIMESTAMP
12/6/2015, 1:22:25 PM
DURATION
PT5.5441347S
TYPE
Microsoft.Web/Sites/config
RESOURCE ID
/subscriptions/47933bfc-a1a9-458a-99a2-fdc8bf2b063b/resourceGroups/GhostonAzure1/providers/Microsoft.Web/Sites/GhostonAzure/config/web
STATUSMESSAGE
{"error":{"code":"InternalServerError","message":""}}
RESOURCE
GhostonAzure/web

---

Thanks and best regards,

John

**Comment by davidebbo** [comment]
Do you know what time zone '12/6/2015, 1:22:25 PM' is referring to? I thought it would be UTC, but I see no records of any APIs called around that time.

One strange thing is that I see the site GhostonAzure having been created way back on December 3rd, and deleted on December 6th. Were you trying this on an existing site or a new site?

**Comment by johnluo** [comment]
@davidebbo 
1. UTC
2. Yup, deployed it and got fault then just deleted it and rebuilt it today.

**Comment by davidebbo** [comment]
Seems the time of latest creation is actually 5:22AM on 12/6. And do see the error at that time.

Please try the following:
- go to https://portal.azure.com/
- go to your GhostonAzure
- Go to settings
- Make some random change like setting the PHP version, and click Save

Does that work or also give some error?

**Comment by johnluo** [comment]
@davidebbo 

 Just deployed 5 min ago

---

OPERATION ID
3C1DBA76C6E1FC0A
TRACKING ID
3e86c2a6-880d-4cb4-9003-5bfea6e8116a
STATUS
BadGateway
PROVISIONING STATE
Running
TIMESTAMP
12/7/2015, 1:32:23 AM
DURATION
PT1M16.9996979S
TYPE
Microsoft.Web/Sites/config
RESOURCE ID
/subscriptions/47933bfc-a1a9-458a-99a2-fdc8bf2b063b/resourceGroups/Ghost-Azured8b3/providers/Microsoft.Web/Sites/Ghost-Azured8b3/config/web
STATUSMESSAGE
{"error":{"code":"InternalServerError","message":""}}
RESOURCE
Ghost-Azured8b3/web

---

**Comment by johnluo** [comment]
@davidebbo 

FYI

![g1](https://cloud.githubusercontent.com/assets/1750848/11614627/2d5fef18-9c83-11e5-870d-42c28816b7a6.jpg)

![g2](https://cloud.githubusercontent.com/assets/1750848/11614629/31cc2742-9c83-11e5-9cd7-ea3e3255679b.jpg)

![g3](https://cloud.githubusercontent.com/assets/1750848/11614630/353a40e4-9c83-11e5-927d-3fe50870c828.jpg)

**Comment by johnluo** [comment]
@davidebbo 

changed something, and save. updated successfully

**Comment by davidebbo** [comment]
Ok, I think I may know the problem. This ARM template is targeting an old version of the API which doesn't support RBAC (role based access control). Can you clarify your access to the subscription? i.e. are you admin, co-admin, or only have RBAC access to part of it? Is it a special subscription?

**Comment by davidebbo** [comment]
Can you try with the deploy button on my fork to see if that helps: https://github.com/davidebbo-test/Ghost-Azure

If you still get errors, please let me know the time and site name of that latest test.

**Comment by felixrieseberg** [comment]
@davidebbo: Thanks for all this help! Shouldn't I use your updated version anyway, even if it doesn't fix this issue? Yes, right?

**Comment by davidebbo** [comment]
Yes, definitely. Just sent PR.

**Comment by johnluo** [comment]
@davidebbo & @felixrieseberg 

Thank you all very much! It's available now! awesome job! :))))

---

Submitting Deployment
Deployment Started
Creating Web Hosting Plan
Creating Website
Setting up Source Control
Fetching changes.
Preparing deployment for commit id '4a7bad13bc'.
Generating deployment script.
Running deployment command... 
Deployment Complete
Manage your site / Browse to http://ghost-azuredb99.azurewebsites.net

---

**Comment by davidebbo** [comment]
@johnluo glad that worked!
