### ISSUE TITLE
core/client folder?

### ISSUE THREAD

**Issue by mkliu** [felixrieseberg/Ghost-Azure#25]
The official repo has a client folder under core, any reason why it's not here?

**Comment by TerribleDev** [comment]
The repo contains source code, not build artifacts...core/client has to be compiled, minified, etc. Otherwise you would be serving a lot of big unminified content...

same reason why core/built exists here but not in the git repo of ghost

**Comment by mkliu** [comment]
i understand that, but why not do grunt init on azure, becoz of speed?

**Comment by felixrieseberg** [comment]
The point of this repo is to provide the _built_ version of Ghost as provided by Ghost - with a few configuration files added to make deployments on Azure easy.

If you want to build Ghost from source, I recommend heading over to the Ghost repository ;-)
