### ISSUE TITLE
what i have to config if I clone your project then deploy to azure web app?

### ISSUE THREAD

**Issue by truongnmt** [felixrieseberg/Ghost-Azure#26]
thanks so much for your great work.
After I clone your project, I create a web app in Azure and set Deployment Source using Dropbox (I'm finding a easy way for non tech guy using this without git and code stuff) to the project folder I cloned. But site just freeze. Please have a look thanks a lot https://www.dropbox.com/sh/t2j0hhazq422e56/AAB0Hiz2paG8ATyvthnd5bjLa?dl=0

**Comment by felixrieseberg** [comment]
Sorry, there's not enough information for me to help you - if you have trouble deploying, why don't you just use the "deploy to Azure" button?

**Comment by truongnmt** [comment]
Thanks for reply so quickly.I want to teach some non-tech guys to create a blog using your tool and Azure, using deploy to Azure button does work, but for example I want to add theme, I have to do with git stuff, I want it go simple because these non-tech guy can't use git, so I want to set deployment source to Dropbox, then if I change theme, I will click sync in Azure.

**Comment by felixrieseberg** [comment]
Just fork the repo - you can then change files as you wish and still use the deploy button :+1: 

![screen shot 2016-03-17 at 10 35 19 am](https://cloud.githubusercontent.com/assets/1426799/13855102/070ad5f0-ec2c-11e5-8145-def317273d09.png)
