### ISSUE TITLE
Multiple Ghost blogs?

### ISSUE THREAD

**Issue by sirvon** [felixrieseberg/Ghost-Azure#27]
What if you want to create 1000s of ghost blogs would you deploy this lib 1000s of times or
is there a more prudent way with only 1 or a few installations?

thanks!

i guess pretty much replicating [Ghost(Pro)'s Business plan](https://ghost.org/pricing/).

**Comment by felixrieseberg** [comment]
You would probably run a virtual machine (or better yet, a cluster) - and not use this at all. Azure Web Apps are really meant for people that don't want to run a lot of something ;-)

In that case, I'd probably just recommend a [Docker Cluster in one your favorite flavors](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-vm-extension/).
