### ISSUE TITLE
Remove loggingEnabled and logDirectory from iisnode.yml

### ISSUE THREAD

**Issue by davidebbo** [felixrieseberg/Ghost-Azure#37]
I think for consistency, it’s best to remove both loggingEnabled and logDirectory. Then it will use the standard pattern:
-   Turn on App Logging in portal
-   Find logs in d:\home\LogFiles\Application

**Comment by felixrieseberg** [comment]
Done.

**Comment by davidebbo** [comment]
`loggingEnabled` is still there.

**Comment by felixrieseberg** [comment]
You know, if Azure would run Node.js apps just fine, I'd also be pro disabling logs - but given that so many people have trouble installing it, I think we should leave it enabled by default. What do you think? Or does leaving it on interfere with the portal settings?

**Comment by davidebbo** [comment]
I think it means it's always enabled and you need to change yml file manually to disable it. But maybe that's not big deal. Ok, let's stay with that until someone complains.
