### ISSUE TITLE
Customising the Casper theme to include Disqus

### ISSUE THREAD

**Issue by RyanONeill1970** [felixrieseberg/Ghost-Azure#39]
I have included Disqus in the post.hbs file and it works. The problem is that it will be overwritten with the next release.

Is there a recommended way to apply customisations to the standard theme? Seems I should copy the Casper theme and customise that instead.

**Comment by RyanONeill1970** [comment]
Ignore my dumb question, I've just stumbled across the code injection option in the Ghost settings which does exactly this.

**Comment by felixrieseberg** [comment]
In the future, an alternative is also to just copy the theme and rename it. New releases (on Azure) only overwrite/add files, they never delete "additional" ones.
