### ISSUE TITLE
Please add ability to specify an Application Insights resource for telemetry during deployment

### ISSUE THREAD

**Issue by nibras85** [felixrieseberg/Ghost-Azure#41]
I'd like to collect telemetry about my Ghost blog instance. It would be nice if I could specify an Application Insights resource to use during the deployment of the Ghost instance to Azure.

**Comment by fboucher** [comment]
You can add it after the deployment.
For the client version go to the admin page of your blog. In the Code Injection section past the code in the Blog Header.

For the server side Application Insights, in the Azure Portal, Go to the Web App.
From the top section select Tools. From the right panel select Extensions. Click the +Add button in the new section that just pop and select Application Insights.

**Comment by nibras85** [comment]
Thank you for your response. I did that and its collecting telemetry properly. This is more of a feature request.. for the deployment script to ask to specify or create an Application Insights resource during deployment. Thanks again.
