### ISSUE TITLE
0.9.0 please

### ISSUE THREAD

**Issue by jpsingleton** [felixrieseberg/Ghost-Azure#42]
https://github.com/TryGhost/Ghost/releases/tag/0.9.0
https://dev.ghost.org/ghost-0-9-0/
http://support.ghost.org/how-to-upgrade/

**Comment by felixrieseberg** [comment]
Thanks, now updated!

**Comment by jpsingleton** [comment]
Awesome thanks. I see you've update https://github.com/AzureWebApps/Ghost-Azure too.
