### ISSUE TITLE
Failed to upgrade to 0.9

### ISSUE THREAD

**Issue by leolorenzoluis** [felixrieseberg/Ghost-Azure#45]
When updating ghost, it looks lit successfully deployed but it won't load anything.
`iisnode was unable to establish named pipe connection to the node.exe process before the process terminated`

**Comment by RyanONeill1970** [comment]
I've seen this too, for some reason the package 'moment-time' (I think) failed to install on checking the logs.

The only way I could get round it was to deploy into a staging slot and upgrade that manually (npm install --production) via the kudu console, then copy my database over.

**Comment by leolorenzoluis** [comment]
I looked at the logs and saw errors on some libraries under node_modules, such as

`ERROR: Cannot find module 'lodash/object/assign'`

or

```
  Cannot find module 'har-validator'
  Cannot find module 'has-ansi'
  Cannot find module 'hawk'
  Cannot find module 'hoek'
  Cannot find module 'html-to-text'
  Cannot find module 'htmlparser2'
  Cannot find module 'http-signature'
  Cannot find module 'iconv-lite'
  Cannot find module 'ini'
  Cannot find module 'intl'
  Cannot find module 'intl-messageformat'
  Cannot find module 'is-my-json-valid'
  Cannot find module 'jodid25519'
  Cannot find module 'jsbn'
  Cannot find module 'json-stringify-safe'
  Cannot find module 'jsonpath'
  Cannot find module 'jsonpointer'
  Cannot find module 'jsprim'
  Cannot find module 'knex'
  Cannot find module 'lodash'
  Cannot find module 'mime-db'
  Cannot find module 'mime-types'
  Cannot find module 'minimatch'
```

I fixed it by removing node_modules folder in Kudu console, then rebuild again. I did have a staging slot where I tested 0.9 first, and didn't really wanna solve it by copying my database over and promoting that one as my production.
