### ISSUE TITLE
Add mail.from in config.js

### ISSUE THREAD

**Issue by aqahtani** [felixrieseberg/Ghost-Azure#49]
Hello,
It would be great if we can amend the email configuration so it can read `mail.from` from an environment variable.  Following the guide on [ghost mail setup](http://support.ghost.org/mail), we could have the following mail config block:

```
mail: {            
    transport: 'SMTP',
    from: process.env.emailFrom, // email from address
    options: {
         service: process.env.emailService,
         auth: {
             user: process.env.emailUsername, // username
             pass: process.env.emailPassword  // password
    }
}
```

This is very important if you would like to make sure that your emails go through trusted sending domains you have configured in your mail service.

**Comment by dwhieb** [comment]
I actually recently opened a PR (https://github.com/felixrieseberg/Ghost-Azure/pull/44) for this.
