### ISSUE TITLE
Selecting an existing App Service Plan / Server Farm

### ISSUE THREAD

**Issue by logiclabs** [felixrieseberg/Ghost-Azure#5]
It doesn't seem to be possible to use an existing server farm/app service plan.  After install, a new App Service Plan gets created with the same name as the site.  Or have I missed something?

It's possible to [move the app manually](http://stackoverflow.com/questions/23685094/is-it-possible-to-move-a-website-to-a-different-web-hosting-plan) post-install, but it'd be nice to be able to pick this during install.

**Comment by felixrieseberg** [comment]
Good question - I hope that @davidfowl, @suwatch, @davidebbo might know if that's somehow possible?

**Comment by davidebbo** [comment]
@logiclabs can you clarify what workflow you are using to install it? e.g. git push your own, gallery, Deploy to Azure button, ...

**Comment by logiclabs** [comment]
@davidebbo The Deploy To Azure button on the github repo's README.

**Comment by davidebbo** [comment]
I think the Deploy Button doesn't support this today. However, if you download the [ARM template](https://github.com/felixrieseberg/Ghost-Azure/blob/master/azuredeploy.json), you can deploy it from the command line using PowerShell and pass an arbitrary server farm.

**Comment by logiclabs** [comment]
Ok.. good to know for future DtoA deployments. Thanks!
