### ISSUE TITLE
No Security Certificate for the Custom Domain

### ISSUE THREAD

**Issue by JijoBose** [felixrieseberg/Ghost-Azure#6]
I added the custom domain in "WebsiteUrl" in Azure.
But When I try to access the admin by "example.com/ghost", it gives Security Certificate Error (NET::ERR_CERT_COMMON_NAME_INVALID)

Please let me know how do I fix this?

ghost-0.7.0

**Comment by TerribleDev** [comment]
see the property forceAdminSSL in config.js

**Comment by JijoBose** [comment]
Thank you :+1:
