### ISSUE TITLE
Update to 0.7.1

### ISSUE THREAD

**Issue by MaherJendoubi** [felixrieseberg/Ghost-Azure#7]
Hi,

Would you please update Ghost  to 0.7.1?
https://github.com/TryGhost/Ghost/releases

Regards,
Maher

**Comment by felixrieseberg** [comment]
Thanks for reminding me - this is now done!

**Comment by MaherJendoubi** [comment]
Hi Felix,
https://github.com/TryGhost/Ghost/releases/tag/0.7.3 is released 5 days ago :)
Thanks
