### ISSUE TITLE
Deployment stuck on 'Setting up source control'

### ISSUE THREAD

**Issue by ch-hristov** [felixrieseberg/Ghost-Azure#74]
I tried to deploy a blog on Azure but the process seems to be stuck on 'Setting up Source Control'. Am I doing something wrong?

**Comment by cbartonnh** [comment]
@ch-hristov did you ever figure this out? I am trying to do this now and seeing the same...

** UPDATE **

Anyone experiencing this just needs to be patient. It tool quite a while but it did eventually finish.

**Comment by ch-hristov** [comment]
Same. Just had to wait a while.
