### ISSUE TITLE
Request for Wiki: How to clone from azure to local to test

### ISSUE THREAD

**Issue by mbecker** [felixrieseberg/Ghost-Azure#8]
Hi,

thank you very much for your work! It would be very nice if you could explain how to load the files from your Azure Webpage to your local machine (via FTP), set the specific parameters to run the same ghost instance locally and push changes via git.

Could you please write a Wiki Page which parameters must be set to run the instance locally?

Thanks in advance

Mats

**Comment by TerribleDev** [comment]
I can do that, I run it locally a lot

**Comment by felixrieseberg** [comment]
@mbecker: Good point! @tparnell8: Awesome, thank you :clap:!

**Comment by mbecker** [comment]
@tparnell8 I would appreciate it very much! Thank you!

**Comment by TerribleDev** [comment]
Sorry I didn't get to this, I will have an opportunity to drop something in about 12 hours from the time of this comment.

**Comment by TerribleDev** [comment]
@mbecker  #9
